### ISSUE TITLE
SNMP access to APC AP7801 not working quite right.

### ISSUE THREAD

**Issue by Numbski** [ecoen66/homebridge-platform-pdu#17]
Not sure what is happening here.  I just got this Rack PDU off of eBay, and it seems to function correctly.  I can get into the webui and into the telnet server on it.  Initially, I was getting access denied errors on the PDU's logs for connecting via SNMP.  Switched private to write+, and that seemed to stop.  Now...well, it seems to work, but also not.  Almost like the MIB isn't correct?  SNMP has never been a strong point of mine, so I'm just kinda winging it over here.  Figured I'd post here in case any of this rang a bell.

The last couple of line is me trying to turn an outlet on/off.  Homebridge tries to comply, but it just gives a useless error.  There's no acknowledgement inside of the apc webui that anything happened at all.

```[12/8/2023, 5:57:24 PM] [Living Room PDU] Executed didFinishLaunching callback
[12/8/2023, 5:57:24 PM] [Living Room PDU] Opened SNMP session.
[12/8/2023, 5:57:24 PM] [Living Room PDU] RackPDU RequestFailedError: NoSuchName: 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.1
    at Req.Session.onSimpleGetResponse [as onResponse] (/homebridge/node_modules/homebridge-platform-pdu/node_modules/net-snmp/index.js:2168:16)
    at Session.onMsg (/homebridge/node_modules/homebridge-platform-pdu/node_modules/net-snmp/index.js:2148:7)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8)
[12/8/2023, 5:57:24 PM] [Living Room PDU] RackPDU Polling Watts 0.0001
[12/8/2023, 5:57:24 PM] [Living Room PDU] RackPDU RequestFailedError: NoSuchName: 1.3.6.1.4.1.318.1.1.12.3.5.1.1.2.1
    at Req.Session.onSimpleGetResponse [as onResponse] (/homebridge/node_modules/homebridge-platform-pdu/node_modules/net-snmp/index.js:2168:16)
    at Session.onMsg (/homebridge/node_modules/homebridge-platform-pdu/node_modules/net-snmp/index.js:2148:7)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8)
[12/8/2023, 5:57:24 PM] [Living Room PDU] Manufacturer varbind returned APC Web/SNMP Management Card (MB:v3.9.2 PF:v3.7.4 PN:apc_hw02_aos_374.bin AF1:v3.7.4 AN1:apc_hw02_rpdu_374.bin MN:AP7801 HR:B2 SN: ZA1510016589 MD:03/07/2015) 
[12/8/2023, 5:57:24 PM] [Living Room PDU] device.manufacturer =  APC
[12/8/2023, 5:57:24 PM] [Living Room PDU] There are 8 outlets.
[12/8/2023, 5:57:24 PM] [Living Room PDU] PDU name RackPDU.
[12/8/2023, 5:57:24 PM] [Living Room PDU] PDU model number AP7801.
[12/8/2023, 5:57:24 PM] [Living Room PDU] PDU serial number ZA1510016589.
[12/8/2023, 5:57:24 PM] [Living Room PDU] PDU firmware version B2.
[12/8/2023, 6:03:28 PM] [Living Room PDU] RackPDU Switching socket 4 to true.
[12/8/2023, 6:03:28 PM] [Living Room PDU] RackPDU Error switching socket 4 to true.
```

**Comment by ecoen66** [comment]
Unfortunately, I don't have one of those to test with.  I am using the published APC PowerNet MIB.  Maybe your device doesn't support all of the MIB entries that are used in my homebridge integration.

**Comment by Numbski** [comment]
Don't suppose you know of there is any way to get more verbose logging?

**Comment by ecoen66** [comment]
Did you turn on "Debug" in the settings for the Plugin within Homebridge?  That's the most output that I coded for.

**Comment by ecoen66** [comment]
You could also try poking around the SNMP MIB using a MIB browser on your PC/Mac.  It would help to load a copy of the APC PowerNet MIB into the browser.  It looks like they are up to version 4.5.2...  https://www.apc.com/us/en/download/document/APC_POWERNETMIB_452_EN/

**Comment by ecoen66** [comment]
Did you figure out what was going on with your PDU?

**Comment by iantait** [comment]
I seem to remember that if I was logged into the apc web interface, it prevented the eve/home app from working properly.

**Comment by Numbski** [comment]
I am on vacation right now, but I will try it without the web interface open when I return home, see how it does.

Tony Shadwick

**Comment by Numbski** [comment]
Found the "solution".  7800 series PDUs are only metered for billing purposes, not switched. For switched outlets in that line, you need 7900 series.
